services:

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php
    hostname: php
    ports:
      - 9000:9000
    volumes:
      - ./wordpress:/app

  mysql:
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: true
    image: mysql:8

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/app